<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Pedro">

    <xacro:property name="PI" value="3.1415" />
    
    <xacro:property name="chassis_mass" value="1"/>
    <xacro:property name="chassis_width" value="0.4" />
    <xacro:property name="chassis_height" value="0.2"/>
    <xacro:property name="chassis_depth" value="0.05"/>

    <!-- wheel properties-->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_xgap" value="0.15"/>
    <xacro:property name="wheel_ygap" value="0.13"/>
    <xacro:property name="wheel_zoff" value="0.0"/>

    <xacro:property name="camera_link" value="0.05" />
    <xacro:property name="front_joint_height" value="${chassis_width}"/>
    <xacro:property name="front_joint_depth" value="${chassis_depth/2}"/>
    
    <!-- Size of square 'camera' box -->
    <!-- Front link of Ackermann -->
    <link name="chassis" />
    
    <joint name="front_joint" type="fixed">
        <parent link="chassis"/>
        <child link="front_link"/>
        <origin xyz="${front_joint_height} 0.0 ${front_joint_depth}"/>
    </joint>
    <link name="front_link">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
        <visual>
            <geometry>
                <box size="0.1 1.0 0.01"/>
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 1.0 0.01"/>
            </geometry>
        </collision>
    </link>
    <!-- a link aligned with the steer direction -->
    <joint name="steer_joint" type="revolute">
    <limit effort="100" lower="-0.5" upper="0.5" velocity="10"/>
    <axis xyz="0 0 1"/>
    <parent link="front_link"/>
    <child link="steer_link"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
  </joint>
    <link name="steer_link">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
        <visual>
            <origin xyz="-0.15 0 0"/>
            <geometry>
                <box size="0.4 0.1 0.01"/>
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="-0.15 0 0"/>
            <geometry>
                <box size="0.4 0.1 0.01"/>
            </geometry>
        </collision>
    </link>
    <!-- <gazebo reference="steer_link">
    <material>Gazebo/Red</material>
  </gazebo> -->
    <!-- the left Ackermann bar -->
    <joint name="front_left_bar_joint" type="revolute">
    <limit effort="100" lower="-0.5" upper="0.5" velocity="10"/>
    <axis xyz="0 0 1"/>
    <parent link="front_link"/>
    <child link="front_left_bar_link"/>
    <origin rpy="0 0 0" xyz="0.0 0.45 0.0"/>
  </joint>
    <link name="front_left_bar_link">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
        <visual>
            <origin xyz="-0.15 0 0"/>
            <geometry>
                <box size="0.4 0.1 0.01"/>
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="-0.15 0 0"/>
            <geometry>
                <box size="0.4 0.1 0.01"/>
            </geometry>
        </collision>
    </link>
    <!-- <gazebo reference="front_left_bar_link">
    <material>Gazebo/Red</material>
  </gazebo> -->
    <!-- the right Ackermann bar -->
    <joint name="front_right_bar_joint" type="revolute">
    <limit effort="100" lower="-0.5" upper="0.5" velocity="10"/>
    <axis xyz="0 0 1"/>
    <parent link="front_link"/>
    <child link="front_right_bar_link"/>
    <origin rpy="0 0 0" xyz="0.0 -0.45 0.0"/>
  </joint>
    <link name="front_right_bar_link">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
        <visual>
            <origin xyz="-0.15 0 0"/>
            <geometry>
                <box size="0.4 0.1 0.01"/>
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="-0.15 0 0"/>
            <geometry>
                <box size="0.4 0.1 0.01"/>
            </geometry>
        </collision>
    </link>
    <!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="continuous">
    <axis xyz="0 1 0"/>
    <parent link="front_left_bar_link"/>
    <child link="front_left_wheel_link"/>
    <origin rpy="0 0 0" xyz="0 0.1 0"/>
  </joint>
    <!-- <gazebo reference="front_left_wheel_link">
    <material>Gazebo/Green</material>
  </gazebo> -->
    <!-- the front right wheel -->
    <joint name="front_right_wheel_joint" type="continuous">
    <axis xyz="0 1 0"/>
    <parent link="front_right_bar_link"/>
    <child link="front_right_wheel_link"/>
    <origin rpy="0 0 0" xyz="0 -0.1 0"/>
  </joint>
    <!-- the Ackerman bar -->
    <joint name="ackermann_joint" type="revolute">
    <limit effort="100" lower="-0.5" upper="0.5" velocity="10"/>
    <axis xyz="0 0 1"/>
    <parent link="steer_link"/>
    <child link="ackermann_bar_link"/>
    <origin rpy="0 0 0" xyz="-0.3 0 0"/>
  </joint>
    <link name="ackermann_bar_link">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
        <visual>
            <geometry>
                <box size="0.1 1.0 0.01"/>
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 1.0 0.01"/>
            </geometry>
        </collision>
    </link>
    <!-- <gazebo reference="front_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="ackermann_bar_link">
    <material>Gazebo/Red</material>
  </gazebo> -->
</robot>